'use strict';

const CONSTANTS = {
    DYNAMODB_SOCKETS_TYPE_GSI: process.env.DYNAMODB_SOCKETS_TYPE_GSI,
    DYNAMODB_SOCKETS_TABLE: process.env.DYNAMODB_SOCKETS_TABLE,
    WEBSOCKET_API_ENDPOINT: process.env.WEBSOCKET_API_ENDPOINT
};

module.exports = CONSTANTS;
